version: 2.1

jobs:
  build:
    docker:
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/python:3.8.4

    steps:
      - checkout
      - run:
          name: create virtual environment, install dependencies
          command: |
            python3.8 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: build pochade
          command: |
            . venv/bin/activate
            pip install --progress-bar=off --upgrade pip 'setuptools<49.2.0'
            pip install --progress-bar=off -r test_requirements.txt
            pip install .

      - run:
          name: run nose tests
          command: |
            . venv/bin/activate
            nosetests -vv --collect-only